hw8.3
mikekidya/homeworks pull request #12
Opened 2017-12-11 09:48 UTC by mikekidya

2017-12-22 09:07 UTC, jzuken requested changes

2017-12-22 09:07 UTC, jzuken commented on 8/3/main.cpp
> +            add(hastTable, subString(string, wordBegin, wordEnd - 1));
проверь, что вся память под строки в этой таблице тоже когда надо очищается

2017-12-22 18:24 UTC, mikekidya commented on 8/3/main.cpp
> +            add(hastTable, subString(string, wordBegin, wordEnd - 1));
Да, память очищается в 49 строке hashtable.cpp

2017-12-22 19:23 UTC, jzuken commented on 8/3/main.cpp
> +            add(hastTable, subString(string, wordBegin, wordEnd - 1));
ну раз я написал, значит не вся очищается :)

2017-12-23 09:51 UTC, mikekidya commented on 8/3/main.cpp
> +            add(hastTable, subString(string, wordBegin, wordEnd - 1));
Да, я нашел -- она не чистится, если строка уже добавлена)
Теперь чистится в строке 73 hashtable.cpp

2017-12-28 11:14 UTC, merged