hw10.2
mikekidya/homeworks pull request #20
Opened 2017-12-18 19:40 UTC by mikekidya

2017-12-21 08:28 UTC, rprtr258 commented on 10/2/string.cpp
> +}
зачем это если существует strlen?

2017-12-21 08:32 UTC, rprtr258 commented on 10/2/string.cpp
> +void concatenation(String *&string, String *secondString)
это странно что функция конкатенации меняет строку которую мы складываем. то есть если я захочу сложить строку с другими строками типа "index :" с строками с числами, то мне надо париться чтобы ее копировать?

2017-12-21 08:32 UTC, rprtr258 commented on 10/2/string.cpp
> +        newString->string[i] = string->string[i];
то же самое делает memcpy

2017-12-21 08:34 UTC, rprtr258 commented on 10/2/string.cpp
> +String *subString(String *string, int begin, int end)
было бы логично сделать индексы константными

2017-12-21 08:35 UTC, rprtr258 commented on 10/2/string.cpp
> +    for (int i = 0; i <= end - begin; i++)
memcpy

2017-12-21 08:37 UTC, rprtr258 commented on 10/2/string.cpp
> +    for (int stringIndex = 0; stringIndex < size - 1; stringIndex++)
что с названиями итераторов? почему они такие большие?

2017-12-21 08:37 UTC, rprtr258 commented on 10/2/string.cpp
> +    }
memcpy

2017-12-21 08:38 UTC, rprtr258 commented on 10/2/string.cpp
> +        stream << string->string[i];
а хранил бы нулевой элемент как в обычной строке мог бы просто указатель на строку вывести

2017-12-21 08:45 UTC, rprtr258 commented on 10/2/main.cpp
> +    while ((currentIndex != -1) && (currentIndex <= stringLength(string) - stringLength(wanted)))
зачем нужно второе условие?

2017-12-24 18:46 UTC, jzuken requested changes

2017-12-24 18:46 UTC, jzuken commented on 10/2/string.cpp
> +        String *slice = subString(string, i, i + stringLength(wanted) - 1);
то есть ты каждый раз будешь подстроку вырезать? не очень-то эффективно

2017-12-24 18:46 UTC, jzuken commented on 10/2/string.cpp
> +        if ((hash(slice) == subHash) && isEqual(wanted, slice))
суть алгоритма в том, чтобы пересчитывать хеш-код инкрементально на основе прошлого

2017-12-24 18:46 UTC, jzuken commented on 10/2/string.cpp
> +int find(String *string, String *wanted, int start)
эти функции никакого отношения к модулю строки не имеют, их отдельно надо

2017-12-28 11:29 UTC, merged