hw2.1
mikekidya/homeworks pull request #45
Opened 2018-09-25 07:31 UTC by mikekidya

2018-12-16 08:52 UTC, jzuken requested changes

2018-12-16 08:52 UTC, jzuken commented on Semester 3/2/hw2.1/src/main/java/group144/kidyankin/Network.java
> +                this.infected.add(comp);
они туда только добавляются, а никто эту коллекцию вроде не использует нигде

2018-12-16 08:52 UTC, jzuken commented on Semester 3/2/hw2.1/src/main/java/group144/kidyankin/Computer.java
> +        return this.name.equals(((Computer) obj).name);
ну вообще тут надо класс объекта проверять ещё

2018-12-16 08:52 UTC, jzuken commented on Semester 3/2/hw2.1/src/test/java/group144/kidyankin/NetworkTest.java
> +        List<Computer> EXPECTED = new ArrayList<>();
как-то он не очень по стайлгайду называется

2018-12-16 08:52 UTC, jzuken commented on Semester 3/2/hw2.1/src/test/java/group144/kidyankin/NetworkTest.java
> +        for (int i = 0; i < numberOfTests; i++) {
а как бы убрать рандом из тестов и проверить саму логику заражения отдельно?

2018-12-16 12:59 UTC, mikekidya commented on Semester 3/2/hw2.1/src/test/java/group144/kidyankin/NetworkTest.java
> +        for (int i = 0; i < numberOfTests; i++) {
А разве логика заражения не проверяется в lineTest и hedgehogTest? Или я не так понимаю?

2018-12-21 07:06 UTC, jzuken commented on Semester 3/2/hw2.1/src/test/java/group144/kidyankin/NetworkTest.java
> +        for (int i = 0; i < numberOfTests; i++) {
ну там проверяются ОС с вероятностью 0 и 1, это не особо интересно. хочется сэмулировать рандом, чтобы всё остальное об этом не знало и работало как обычно

2018-12-21 07:06 UTC, jzuken commented on Semester 3/2/hw2.1/src/test/java/group144/kidyankin/NetworkTest.java
> +        for (int i = 0; i < numberOfTests; i++) {
внезапно оказалось, что тогда коммент не отправился :)

2018-12-21 07:50 UTC, merged